import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.6.1" // available: "0.7.0"

    const val com_android_tools_build_gradle: String = "3.6.3"

    const val play_services_analytics: String = "17.0.0"

    const val play_services_ads_lite: String = "19.1.0"

    const val org_jetbrains_kotlin: String = "1.3.72"

    const val flexible_adapter_ui: String = "1.0.0"

    const val androidx_lifecycle: String = "2.2.0"

    const val firebase_analytics: String = "17.4.1"

    const val play_services_base: String = "17.2.1"

    const val constraintlayout: String = "1.1.3"

    const val flexible_adapter: String = "5.1.0"

    const val firebase_config: String = "19.1.4"

    const val google_services: String = "4.3.3"

    const val firebase_core: String = "17.4.1"

    const val fragment_ktx: String = "1.2.4"

    const val recyclerview: String =  "1.1.0"

    const val lint_gradle: String = "26.6.3"

    const val android_ui: String = "1.2"

    const val preference: String = "1.1.1"

    const val appcompat: String = "1.1.0"

    const val superslim: String = "0.4.13"

    const val core_ktx: String = "1.2.0"

    const val material: String = "1.1.0"

    const val okhttp: String = "4.6.0"

    const val aapt2: String = "3.6.3-6040484"

    const val swipeRefreshLayout = "1.0.0"

    /**
     * Current version: "5.4.1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.4"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
